# -*-Dockerfile-*-
FROM arm64v8/debian:buster
RUN apt update && \
    apt install -y build-essential curl libcurl4-openssl-dev libsqlite3-dev pkg-config wget git
RUN mkdir -p /usr/src && \
    cd /usr/src && \
	git clone https://github.com/abraunegg/onedrive.git && \
	cd /usr/src/onedrive && \
	wget https://github.com/ldc-developers/ldc/releases/download/v1.23.0/ldc2-1.23.0-linux-aarch64.tar.xz && \
    tar -xvf ldc2-1.23.0-linux-aarch64.tar.xz && \
	mv ldc2-1.23.0-linux-aarch64 / && \
	./configure DC=/ldc2-1.23.0-linux-aarch64/bin/ldmd2 && \
    make clean && \
    make && \
    make install

FROM arm64v8/debian:buster-slim
ENTRYPOINT ["/entrypoint.sh"]
RUN apt update && \
    apt install -y gosu libcurl3 libsqlite3-0 && \
    rm -rf /var/*/apt && \
    mkdir -p /onedrive/conf /onedrive/data
COPY contrib/docker/entrypoint.sh /
COPY --from=0 /usr/local/bin/onedrive /usr/local/bin/
